### ISSUE TITLE
Radio input element is not displayed correctly

### ISSUE THREAD

**Issue by taenzer** [robsontenorio/mary#343]
### maryUI version

1.25

### daisyUI version

4.7.3

### Livewire version

3.4

### What browsers are affected?

Firefox, Microsoft Edge

### What happened?

Hey, I just started with MaryUi and first created a form with a simple radio input (as you can see i'am also using breeze, hence the mary prefix):

```blade
    <x-mary-form wire:submit="save">
        <x-mary-radio label="Transaktionsart wählen:" :options="$options" wire:model="transactionType"/>
    </x-mary-form>
```

To get the options, i used the function mentioned in the maryui documentation:
```php
$options = App\Models\User::take(3)->get();
```
Unfortunately, the component does not render correctly in the browser. I can't find the styling error using the browser's developer tools either:
![image](https://github.com/robsontenorio/mary/assets/72893392/f1c43931-f803-4b15-b3b3-8a707592b963)
![image](https://github.com/robsontenorio/mary/assets/72893392/dd59961a-c7ce-4f4d-854c-355de668a11c)

Unfortunately, I'm at the end of my knowledge and hope that you might have an idea as to what's causing the problem.

If you need more information, let me know!

Thank you very much for your help, best regards, Moritz

**Comment by robsontenorio** [comment]
This usually happens if you have a lot of things on your “app.css” or any extra css file, related to radio style. 

Gradually  remove some styles from your app to try to spot the issue.

**Comment by taenzer** [comment]
Thanks for your reply! There is not much in my app.css, especially no styling of (radio) inputs. I've only just set up the project. Apart from a few models, the form is the first thing I created.

To be safe, I deleted everything from the app.css. However, it still doesn't display properly. (I also cleared cache):
![image](https://github.com/robsontenorio/mary/assets/72893392/05d668a1-cde3-4397-8c0f-5b43ebb43cd7)

**Comment by robsontenorio** [comment]
Please, share your original app.css and any additional stylesheet is loaded.

**Comment by taenzer** [comment]
Here is my complete `/resources/css/app.css` file (no other css files are used):
```css
@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --main: 59, 85, 255;
  --col1: 24, 27, 43;
  --col2: 31, 35, 56;
  --bg: 222, 222, 222;
  --textLight: 220, 220, 220;
  --textDark: 17, 17, 17;
  --littleLighter: 240, 240, 240;
  --Fheading: "Montserrat";
  --Fcontent: "Montserrat";
  --IconSolid: "Material Icons";
}



h1, h2, h3 {
  text-transform: uppercase;
  font-weight: 900;
}
h2{
  font-weight: 600;
  font-size: 1.2em;
  letter-spacing: 1px;
}

h3{
  font-weight: 400;
  font-size: 1em;
}

a{
  text-decoration: none;
  color: inherit;
}

/* Stuff */
.moneyInput{
  position: relative;
}

.moneyInput input[type="number"]{
  padding-right: 3em;
}

.moneyInput:after{
  content: "€";
  position: absolute;
  line-height: 100%;
  right: 1.5em;
  top: 50%;
  transform: translate(50%, -50%);
}

.wrapper{
  display: grid;
  grid-template-columns: repeat(6, 1fr);
  grid-template-rows: 8fr 100px;
  height: 100vh;

}

#menu{
  grid-area:  1 / 1 / 1 / 1;
  background: rgb(var(--col1));
  color: rgb(var(--textLight));
  padding: 30px;
  overflow-y: auto;
  min-width: 250px;
}


 #menu img{
   max-width: 65%;
   height: auto;
   display: block;
}

#bottom{
  grid-area:  2 / 1 / 2 / 1;
  background: rgb(var(--col2));
  color: rgb(var(--textLight));
  padding: 30px;
  position: relative;
}

#content{
  grid-area: 1 / 2 / 3 / 7;
  background: rgb(var(--bg));
  box-shadow: inset 54px 0px 50px -70px #00000080;
  padding: 50px 5vw;
  overflow-y: auto;
  position: relative;
}
.ui-helper-hidden-accessible{
  display: none;
}

/* Arrows */
.long-arrow-right,
.long-arrow-left{
  display: block;
  margin: 30px auto;
  width: 25px;
  height: 25px;
  border-top: 2px solid #000;
  border-left: 2px solid #000;
}
.arrow-right,
.long-arrow-right{
 transform: rotate(135deg);
}

.arrow-left,
.long-arrow-left{
 transform: rotate(-45deg);
}
.long-arrow-right::after,
.long-arrow-left::after{
  content: "";
  display: block;
  width: 2px;
  height: 45px;
  background-color: black;
  transform: rotate(-45deg) translate(15px, 4px);
  left: 0;
  top: 0;
}


.ui-autocomplete{
  background: rgb(255 255 255 / 64%);
  list-style: none;
  padding: 20px;
}
.ui-autocomplete-category{
  font-weight: 600;
  padding: 10px 0;
  cursor: default;
}

.ui-menu-item{
  background: #ebebeb;
  padding: 10px;
  transition: all 0.1s;
  cursor: pointer;
}

.ui-menu-item.neuerKontakt:before{
  content: "\e7fe";
  font-family: 'Material Icons';
  vertical-align: bottom;
  display: inline-block;
  line-height: 1em;
  margin-right: 5px;
  font-size: 1.1em;

  /* Support for all WebKit browsers. */
  -webkit-font-smoothing: antialiased;
  /* Support for Safari and Chrome. */
  text-rendering: optimizeLegibility;

  /* Support for Firefox. */
  -moz-osx-font-smoothing: grayscale;

  /* Support for IE. */
  font-feature-settings: 'liga';
}

.ui-menu-item:not(:last-child){

  margin-bottom: 10px;

}

.ui-menu-item:hover{
  background: rgb(var(--main));
  color: rgb(var(--textLight));
}
.subt{
  display: block;
  font-size: 0.8em;
  opacity: 0.7;
}

/* Scrollbar */
::-webkit-scrollbar{
  width: 0.5em;
}

::-webkit-scrollbar-track{
  background: transparent;
  margin: 5px;
}

::-webkit-scrollbar-thumb{
  border-radius: 100vw;
  background: rgba(var(--main), 1);
}

/* MOBILE */
@media screen and (max-width: 1100px) {
  #menu{
    z-index: 1000;
    position: fixed;
    width: 100%;
    height: 100%;
    display: none;
  }

  #mobile-menu-trigger{
    display: block;
  }

  #menu img{
    max-width: 100px;
  }

  #menu.open{
    display: block;
  }
  #content {
    grid-area: 1 / 1 / 1 / 7;
    box-shadow: inset 0 -54px 50px -70px #00000080;
  }

  #bottom{
    grid-area: 2 / 1 / 2 / 7;
  }

}

```
