### ISSUE TITLE
Input search default on choices component 

### ISSUE THREAD

**Issue by kmaphane** [robsontenorio/mary#420]
### maryUI version

1.30.3

### daisyUI version

4.10.1

### Livewire version

3.4.12

### What browsers are affected?

Microsoft Edge

### What happened?

![image](https://github.com/robsontenorio/mary/assets/80934965/96310f4c-a3ed-4f96-bead-f596f1cb7a35)

I get the search box in my choices component. This is the code I am using: 

```blade
<div>
        <label>
            <div class="label">
                <span class="label-text font-black text-base-300">
                    Select statistics
                </span>
            </div>
            <x-mary-choices
                icon="o-chart-bar"
                :options="$statistics"
                wire:model.live="selectedStatistics"
                compact
                compact-text="Select statistics"
                allow-all
                inline
                class="select-ghost select-lg border-base-300 text-base-300 focus:border-base-100"
            />
        </label>
    </div>
```

This is the rendered HTML:

```HTML
<input x-ref="searchInput" @input="focus()" :required="isRequired &amp;&amp; isSelectionEmpty" :readonly="isReadonly || isDisabled || ! isSearchable" :class="(isReadonly || isDisabled || !isSearchable || !focused) &amp;&amp; '!w-1'" class="outline-none mt-0.5 bg-transparent w-20 !w-1" readonly="readonly">
```

**Comment by robsontenorio** [comment]
What is your OS ?
I can't reproduce it on MacOS Edge.

1) Try to remove this to test it `class="select-ghost select-lg border-base-300 text-base-300 focus:border-base-100"`
2) Please, use the browser INSPECTOR to see if any external CSS is overriding the style of this "search box".

**Comment by kmaphane** [comment]
Hi,

Thanks for the response. 

I use Windows 11. 

There is nothing I can see that is overriding the styles, unless I need to check further:

element.style {
}
.outline-none {
    outline: 2px solid transparent;
    outline-offset: 2px;
}
.bg-transparent {
    background-color: transparent;
}
.\!w-1 {
    width: 0.25rem !important;
}
.w-20 {
    width: 5rem;
}
.mt-0\.5 {
    margin-top: 0.125rem;
}
[type='text'], input:where(:not([type])), [type='email'], [type='url'], [type='password'], [type='number'], [type='date'], [type='datetime-local'], [type='month'], [type='search'], [type='tel'], [type='time'], [type='week'], [multiple], textarea, select {
    -webkit-appearance: none;
    -moz-appearance: none;
    appearance: none;
    background-color: #fff;
    border-color: #6b7280;
    border-width: 1px;
    border-radius: 0px;
    padding-top: 0.5rem;
    padding-right: 0.75rem;
    padding-bottom: 0.5rem;
    padding-left: 0.75rem;
    font-size: 1rem;
    line-height: 1.5rem;
    --tw-shadow: 0 0 #0000;
}
button, input, optgroup, select, textarea {
    font-family: inherit;
    font-feature-settings: inherit;
    font-variation-settings: inherit;
    font-size: 100%;
    font-weight: inherit;
    line-height: inherit;
    letter-spacing: inherit;
    color: inherit;
    margin: 0;
    padding: 0;
}

**Comment by kmaphane** [comment]
Sorry as a follow up, i removed the classes, but nothing changed.

**Comment by robsontenorio** [comment]
Yes, it has todo. If you remove this block it works fine.


My advice is to not fight against the design system. Because, daisyUI provides it to keep consistence across all components. If you want to change the appearance, please refer to daisyUI docs to proper do it.



```css
[type='text'], input:where(:not([type])), [type='email'], [type='url'], [type='password'], [type='number'], [type='date'], [type='datetime-local'], [type='month'], [type='search'], [type='tel'], [type='time'], [type='week'], [multiple], textarea, select {
-webkit-appearance: none;
-moz-appearance: none;
appearance: none;
background-color: #fff;
border-color: #6b7280;
border-width: 1px;
border-radius: 0px;
padding-top: 0.5rem;
padding-right: 0.75rem;
padding-bottom: 0.5rem;
padding-left: 0.75rem;
font-size: 1rem;
line-height: 1.5rem;
--tw-shadow: 0 0 #0000;
}
```
