### ISSUE TITLE
Modal background does not cover empty space on the right side

### ISSUE THREAD

**Issue by Hassanbhb** [robsontenorio/mary#637]
### maryUI version

1.35.8

### daisyUI version

4.12.10

### Livewire version

3.5.6

### What browsers are affected?

Chrome, Microsoft Edge

### What happened?

The modal component leaves an empty space on the right side.

![image](https://github.com/user-attachments/assets/af81a367-86c1-4d78-9a52-b0643d15e9e8)

I tested chrome & edge, both have the issue. not sure about the rest.

**Comment by anfeichtinger** [comment]
This is a bug related to daisy-ui and is not mary-ui specific. There is a discussion about a potential fix [here](https://github.com/saadeghi/daisyui/issues/3040#issuecomment-2250530354).

For me the following css will hide the scollbar when the modal is open (this does shift the layout a bit though). There are some other solutions you can try in the issue above.
```css
:root:has(
    :is(
        .modal-open,
        .modal:target,
        .modal-toggle:checked + .modal,
        .modal[open]
      )
  ) {
  scrollbar-gutter: unset;
}
```

We can discuss putting this inside of the `app.css` stub. @robsontenorio what is your opinion?
