### ISSUE TITLE
Theme manual activation not working

### ISSUE THREAD

**Issue by lchevalot** [robsontenorio/mary#850]
### maryUI version

2.0.1

### daisyUI version

5.0.13

### Livewire version

3.6.2

### What browsers are affected?

Chrome

### Description

When using the [manual theme toggle](https://mary-ui.com/docs/components/theme-toggle#manual-activation) and clicking on the button dispatching the event, nothing happens.

### Code

My **app.css** file

```css
@import 'tailwindcss';

/* MaryUI + DaisyUI */
@plugin "daisyui" {
    themes: retro --default, aqua --prefersdark;
}

@source "../../vendor/robsontenorio/mary/src/View/Components/**/*.php";

@custom-variant dark (&:where(.dark, .dark *));

@source '../../vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php';
@source '../../storage/framework/views/*.php';
@source '../**/*.blade.php';
@source '../**/*.js';

@theme {
    --font-sans: 'Instrument Sans', ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji',
    'Segoe UI Symbol', 'Noto Color Emoji';
}
```

The HTML code where i've putted the theme toggle (**app.blade.php**)

```blade
...
<x-slot:actions>
    <x-button icon="o-swatch" @click="$dispatch('mary-toggle-theme')" />
    <x-theme-toggle class="hidden" darkTheme="aqua" lightTheme="retro" />
</x-slot:actions>
...
```

Note that i don't have any `<x-theme-toggle />` anywhere else in the project. I've also tried to refresh my browser and restart npm obviously. I've also tried not putting any manual light/dark theme in the `<x-theme-toggle />`.

Also the `<x-theme-toggle />` component alone itself works.

Tell me if i did something wrong.
